### ISSUE TITLE
[BUG] Current Tiles Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#599]
Current Tiles Collection doesn't seem to be getting passed sometimes. The tiles in the video should be getting both activated and unhidden, but are only getting activated.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/a9db0e5d-9e63-4cb1-93b4-25e36f5970e7

MATT 11.06
Foundry 11.308

**Comment by ironmonk88** [comment]
I think this is fixed?

**Comment by Crowguard** [comment]
Still not showing the tiles in this setup.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/aaed2bfa-f864-4189-9e00-d6dd829f3d9c


MATT 11.07

**Comment by ironmonk88** [comment]
Moving this to low priority.
I know what the issue is, but it affects A LOT of actions.  Not all of them alter the `Current Collection` and `Activate` is one of those.
So the mean time fix would be to use `Set Current Collection` and run from that, while I think of what the best way to solve it would be.
