### ISSUE TITLE
[BUG] MATT cannot distinguish between a double-click and two single-clicks

### ISSUE THREAD

**Issue by yorkshirelandscape** [ironmonk88/monks-active-tiles#728]
**Describe the bug**
MATT cannot distinguish between a double-click and two single-clicks. Left and right click behaviors are slightly different.

**To Reproduce**

1. Create a tile that will do different things depending on whether you click or double-click.
2. Double-click on the tile. 
**Expected:** The double-click action occurs.
**Actual:** The click and double-click actions both occur.

1. Create a tile that will do different things depending on whether you right-click or double right-click. This is what I was doing initially, a slight modification to Image Selector. I made click advance, double-click go back, and right-click open the dialog.
2. Double right-click on the tile.
**Expected:** The double right-click action occurs.
**Actual:** The double right-click action occurs and the right-click action occurs twice.

**Screenshots**
[matt_double_click.webm](https://github.com/ironmonk88/monks-active-tiles/assets/1088016/62fbc550-e7a6-428e-a8e5-3cfcc2f4fc53)

**Please complete as much of the following information as possible:**
 - Browser: Chrome v122
 - Foundry Version: V11
 - System: PF2e
 - Module version: 11.22
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No, seems unlikely.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by yorkshirelandscape** [comment]
I just tried it out and now it only generates one dialog when I double right-click, but the bigger problem still remains. It can't distinguish between a double-click and two single-clicks. If I want it to do two different thing on click and double-click, it won't work because it will always run the the single click action before you finish double-clicking.
