### ISSUE TITLE
[BUG] Distance Filter

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#945]
<img width="538" height="532" alt="Image" src="https://github.com/user-attachments/assets/ca72c548-d108-419c-b4dd-6f8b89fb1e99" />

Always says pixels, even when its squares.

Edit: It is fact, actually measuring pixels, even when you have it set to grid.

Foundry 13.347
MATT 13.05

**Comment by cmcoffin** [comment]
Should be fixed in https://github.com/ironmonk108/monks-active-tiles/pull/989

**Comment by Crowguard** [comment]
Not actually fixed.

For pre-existing tiles, it still measures in pixels until you open the tile's actions, edit the distance filter (don't need to change anything, just save), and save the tile. The existing data is still there for grid units, but its using pixels until manually updated anyway.

Foundry 13.351
MATT 13.06
